DESIGN:
  SUBLEN: 4096

FEATURE:
  USED_F: ['Mean']
  USED_THRESHOLD: ['log','gause','Z','percentile','boxplot']

TRAIN:
  NORMAL_PATH: 'data\datasets\BUCT\0normal.csv'

INFERENCE:
  UNKWON_PATH: 'data\datasets\BUCT\1dybph.csv'
  MODEL_PATH: "output/buct_lstm.pth"

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "BUCT_test" 