DESIGN:
  SUBLEN: 4096

FEATURE:
  USED_F: ['Mean']
  NEED_VIEW: False

TRAIN:
  NORMAL_PATH: 'data\datasets\BUCT\0normal.csv'
  FAULT_PATH: 'data\datasets\BUCT\2dybph.csv'

OUTPUT:
  MODEL_DIR: "output"
  MODEL_NAME: "buct_lstm.pth"

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "train" 
  ITER_INTERVAL: 100
  EPOCH_INTERVAL: 100

SOLVER:
  MAX_EPOCHS: 800
  BASE_LR: 1e-4