FEATURE:
  USED_F: ['Mean']
  USED_THRESHOLD: ['Z']
  NEED_VIEW: True

TRAIN:
  NORMAL_PATH: 'data/datasets/CWRU/97.csv'
  FAULT_PATH: 'D:\development\dataset\CWRU\csv\262.csv'
  
INFERENCE:
  UNKWON_PATH: 'D:\development\dataset\CWRU\csv\161.csv'
  MODEL_PATH: "output/cwru_lstm.pth"

OUTPUT:
  MODEL_DIR: "output"
  MODEL_NAME: "cwru_lstm.pth"


LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "test" 