FEATURE:
  USED_F: ['KV']
  USED_THRESHOLD: ['Z']

TRAIN:
  NORMAL_PATH: 'data/datasets/CWRU/97.csv'

INFERENCE:
  UNKWON_PATH: 'D:\development\dataset\CWRU\csv\213.csv'
  MODEL_PATH: "output/cwru_lstm.pth"

LOG:
  OUTPUT_TO_FILE: False
  PREFIX: "CWRU_draw" 