FEATURE:
  USED_F: ['Mean']
  USED_THRESHOLD: ['log','gause','Z','percentile','boxplot']

TRAIN:
  NORMAL_PATH: 'data/datasets/CWRU/97.csv'

INFERENCE:
  UNKWON_PATH: 'data/datasets/CWRU/122.csv'
  MODEL_PATH: "output/cwru_lstm.pth"

LOG:
  OUTPUT_TO_FILE: False
  PREFIX: "draw" 