FEATURE:
  USED_F: ['RVF']

TRAIN:
  NORMAL_PATH: 'data/datasets/CWRU/97.csv'
  FAULT_PATH: 'data/datasets/CWRU/189.csv'

OUTPUT:
  MODEL_DIR: "output"
  MODEL_NAME: "cwru_lstm.pth"

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "train" 