DESIGN:
  FPIECE: 100 # num of pieces drawed from feature series

FEATURE:
  USED_F: ['SV']
  USED_THRESHOLD: ['log','gause','Z','percentile','boxplot']

DENOISE:
  NEED: False
  METHOD: 'wavelet'
  WAVELET: 'db4'
  LEVEL: 6
  SHOW_NEED: True

TRAIN:
  NORMAL_PATH: 'D:\development\dataset\CincinnatiIMS\output\1st_test_3bearing\2003.10.22.12.06.24.csv'
  FAULT_PATH: 'D:\development\dataset\CincinnatiIMS\output\1st_test_3bearing\2003.11.25.23.39.56.csv'
  
INFERENCE:
  UNKWON_PATH: 'D:\development\dataset\CincinnatiIMS\output\1st_test_3bearing\2003.11.25.23.39.56.csv'
  MODEL_PATH: 'output/ims_lstm.pth'
  TEST_CONTENT: 'D:\development\dataset\CincinnatiIMS\output\1st_test_3bearing'

OUTPUT:
  MODEL_DIR: "output"
  MODEL_NAME: "ims_lstm.pth"

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "IMS_test"
