FEATURE:
  NEED_VIEW: True

TRAIN:
  NORMAL_PATH: 'D:\development\dataset\CincinnatiIMS\output\1st_test_4bearing\2003.10.22.12.19.13.csv'
  FAULT_PATH: 'D:\development\dataset\CincinnatiIMS\output\1st_test_4bearing\2003.11.25.23.39.56.csv'

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "IMS_find" 