FEATURE:
  USED_F: ['Meanf']
  USED_THRESHOLD: ['log','gause','Z','percentile','boxplot']

DENOISE:
  NEED: False
  METHOD: 'wavelet'
  WAVELET: 'db4'
  LEVEL: 3
  SHOW_TYPE: 'both'

TRAIN:
  NORMAL_PATH: 'D:\development\dataset\XJTU-SY_Bearing_Datasets\XJTU-SY_Bearing_Datasets\35Hz12kN\Bearing1_5\1.csv'
  
INFERENCE:
  MODEL_PATH: 'output/xjtu_lstm.pth'
  TEST_CONTENT: 'D:\development\dataset\XJTU-SY_Bearing_Datasets\XJTU-SY_Bearing_Datasets\35Hz12kN\Bearing1_5'

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "XJTU_test" 