FEATURE:
  USED_F: ['KV','CF']
  NEED_VIEW: False

TRAIN:
  NORMAL_PATH: 'data\datasets\XJTU-SY\Bearing1_1\1.csv'
  FAULT_PATH: 'data\datasets\XJTU-SY\Bearing1_1\123.csv'

OUTPUT:
  MODEL_DIR: "output"
  MODEL_NAME: "xjtu_lstm.pth"

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "train" 
  ITER_INTERVAL: 100
  EPOCH_INTERVAL: 100