FEATURE:
  USED_F: ['KV']
  USED_THRESHOLD: ['log','gause','Z','percentile','boxplot']

TRAIN:
  NORMAL_PATH: 'data/datasets/XJTU-SY/Bearing1_1/1.csv'
  
INFERENCE:
  UNKWON_PATH: 'data/datasets/XJTU-SY/Bearing1_1/61.csv'
  MODEL_PATH: 'output/xjtu_lstm.pth'
  TEST_CONTENT: 'D:\development\dataset\XJTU-SY_Bearing_Datasets\XJTU-SY_Bearing_Datasets\35Hz12kN\Bearing1_1'

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "XJTU_test" 