FEATURE:
  NEED_VIEW: True

TRAIN:
  NORMAL_PATH: 'D:\development\dataset\XJTU-SY_Bearing_Datasets\XJTU-SY_Bearing_Datasets\40Hz10kN\Bearing3_3\4.csv'
  FAULT_PATH: 'D:\development\dataset\XJTU-SY_Bearing_Datasets\XJTU-SY_Bearing_Datasets\40Hz10kN\Bearing3_3\371.csv'

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "XJTU_find" 