FEATURE:
  USED_F: ['KV','CF']
  USED_THRESHOLD: ['log','gause','Z','percentile','boxplot']

TRAIN:
  NORMAL_PATH: 'data/datasets/XJTU-SY/Bearing1_1/1.csv'
  
INFERENCE:
  UNKWON_PATH: 'data/datasets/XJTU-SY/Bearing1_1/61.csv'
  MODEL_PATH: 'output/xjtu_lstm.pth'

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "XJTU_test" 