FEATURE:
  NEED_VIEW: True

TRAIN:
  NORMAL_PATH: 'D:\development\dataset\XJTU-SY_Bearing_Datasets\XJTU-SY_Bearing_Datasets\35Hz12kN\Bearing1_1\4.csv'
  FAULT_PATH: 'D:\development\dataset\XJTU-SY_Bearing_Datasets\XJTU-SY_Bearing_Datasets\35Hz12kN\Bearing1_1\123.csv'

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "XJTU_find" 