FEATURE:
  USED_F: ['fMean']
  NEED_VIEW: False

TRAIN:
  NORMAL_PATH: 'data/datasets/XJTU-SY/Bearing1_2/1.csv'
  FAULT_PATH: 'data/datasets/XJTU-SY/Bearing1_2/161.csv'

OUTPUT:
  MODEL_DIR: "output"
  MODEL_NAME: "xjtu_lstm.pth"

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "XJTU_train" 
  ITER_INTERVAL: 100
  EPOCH_INTERVAL: 100