FEATURE:
  USED_F: ['fMean']
  USED_THRESHOLD: ['log','gause','Z','percentile','boxplot']

TRAIN:
  NORMAL_PATH: 'data/datasets/XJTU-SY/Bearing1_2/1.csv'
  
INFERENCE:
  UNKWON_PATH: 'data/datasets/XJTU-SY/Bearing1_2/91.csv'
  MODEL_PATH: 'output/xjtu_lstm.pth'

LOG:
  OUTPUT_TO_FILE: False
  PREFIX: "XJTU_draw" 