FEATURE:
  USED_F: ['FC']
  USED_THRESHOLD: ['Z']

DENOISE:
  NEED: False
  SHOW_METHOD: 'wavelet'
  SMOOTH_STEP: 3
  SHOW_WAVELET: 'db4'
  SHOW_LEVEL: 3
  SHOW_TYPE: 'denoised only'

TRAIN:
  NORMAL_PATH: 'D:\development\datasets\XJTU-SY_Bearing_Datasets\XJTU-SY_Bearing_Datasets\40Hz10kN\Bearing3_4\1.csv'
  
INFERENCE:
  UNKWON_PATH: 'D:\development\datasets\XJTU-SY_Bearing_Datasets\XJTU-SY_Bearing_Datasets\40Hz10kN\Bearing3_4\2.csv'
  MODEL_PATH: 'output/xjtu_lstm.pth'
  TEST_CONTENT: ''

LOG:
  OUTPUT_TO_FILE: True
  PREFIX: "XJTU_test" 

SOLVER:
  MAX_EPOCHS: 100